services:
  metube:
    mem_limit: 1024m
    cpus: 1

  jellyfin:
    mem_limit: 2g
    cpus: 2

  seerr:
    mem_limit: 1024m
    cpus: 1

  prowlarr:
    mem_limit: 1024m
    cpus: 1

  sonarr:
    mem_limit: 1024m
    cpus: 1

  radarr:
    mem_limit: 1024m
    cpus: 1

  bazarr:
    mem_limit: 1024m
    cpus: 0.5

  qbittorrent:
    mem_limit: 2g       
    mem_reservation: 400m
    cpus: 1.5

  flaresolverr:
    mem_limit: 2g        
    cpus: 2
