services:
  immich-server:
    mem_limit: 2.5g
    cpus: 2

  immich-machine-learning:
    mem_limit: 4g           
    cpus: 2.5

  database:
    mem_limit: 2g
    cpus: 1

  redis:
    mem_limit: 256m
