services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "${BIND_IP:-0.0.0.0}:80:80"
      - "${BIND_IP:-0.0.0.0}:81:81"
      - "${BIND_IP:-0.0.0.0}:443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - homelab_net

networks:
  homelab_net:
    external: true